import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import DescriptionList from "@/components/custom/DescriptionList";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen p-24 max-w-[960px] mx-auto grid">
          <div>{children}</div>
          <div>
            <DescriptionList />
          </div>
        </main>
      </body>
    </html>
  );
}
